In [5]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np


In [3]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [7]:
type(arr)

numpy.ndarray

In [11]:
arr.shape

(5,)

In [13]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[3,4,5,6,7]
arr=np.array([my_list1,my_list2,my_list3])

In [15]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [17]:
arr.shape

(3, 5)

In [19]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [21]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [27]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [31]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [37]:
arr=np.arange(1,20,step=2)

In [39]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [48]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [50]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
##copy function and broadcasting
arr[3:]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [56]:
arr1=arr

In [58]:
arr1[0:3]=500
arr

array([500, 500, 500, 100, 100, 100, 100, 100, 100, 100])

In [60]:
arr
## this is arr1 is referencing to the arr variable so that is  sharing   the same memory location of arr therefore it changes the arr 

array([500, 500, 500, 100, 100, 100, 100, 100, 100, 100])

In [62]:
arr1=arr.copy()

In [66]:
arr1[0:3]=200
arr1

array([200, 200, 200, 100, 100, 100, 100, 100, 100, 100])

In [68]:
arr
## here the arr1 makes the copy of arr therefore it is not sharing the memory location , so this not affect in arr

array([500, 500, 500, 100, 100, 100, 100, 100, 100, 100])

In [7]:
### some conditions very useful in exploratory data analysis
import numpy as np
my_list1=[100,101,102,200,201,202]
arr2=np.array(my_list1)
arr2


array([100, 101, 102, 200, 201, 202])

In [11]:
arr2>200

array([False, False, False, False,  True,  True])

In [13]:
arr2[arr2>199]

array([200, 201, 202])